### ISSUE TITLE
Pin Y11

### ISSUE THREAD

**Issue by peterhinch** [mcauser/Fritzing-Part-Micro-Python-pyboard#1]
There is something odd about this pin. In Fritzing create a new sketch and, in the schematic editor, try linking pins Y9 and Y11. I'm new to Fritzing but it does behave differently from the other pins I've tried.

**Comment by mcauser** [comment]
I had an incorrect y position on connector10terminal (Y11).

**Comment by mcauser** [comment]
Fixed in: https://github.com/mcauser/Fritzing-Part-Micro-Python-pyboard/pull/2
